name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What did you expect, and what happened instead?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Minimal steps or a minimal Astra JSON module that reproduces the issue.
      render: shell
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `astra --version` (or package version)
    validations:
      required: true
